name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main # Default release branch
      - develop
      - 'releases/**'
    paths:
      - 'Plotly.Blazor/**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test
